# Generated by Django 4.2.2 on 2023-06-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=50)),
                ('path', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='published')),
            ],
        ),
    ]
