# Generated by Django 4.2.2 on 2023-07-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=200)),
                ('employees', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='published'),
        ),
    ]
