# Generated by Django 4.2.2 on 2023-08-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_firm_type_firm_nace_firm_orgnr_firm_orgtype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firm',
            name='address',
            field=models.CharField(default='Hammersborggata 2', max_length=200),
        ),
        migrations.AddField(
            model_name='firm',
            name='municipality',
            field=models.CharField(default='Oslo', max_length=100),
        ),
        migrations.AddField(
            model_name='firm',
            name='postal',
            field=models.CharField(default='Oslo', max_length=100),
        ),
        migrations.AddField(
            model_name='firm',
            name='postalcode',
            field=models.CharField(default='0181', max_length=10),
        ),
        migrations.AlterField(
            model_name='firm',
            name='nace',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
