# Generated by Django 4.2.2 on 2023-08-18 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_firm_address_firm_municipality_firm_postal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmContacted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='user_id', max_length=10)),
                ('contacted', models.BooleanField(default=False)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacted', to='app.firm')),
            ],
        ),
    ]
