# Generated by Django 4.2.2 on 2023-09-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_firmcontacted_firm_firmcontacted_orgnr'),
    ]

    operations = [
        migrations.AddField(
            model_name='firm',
            name='municipality_nr',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='firm',
            name='stiftelsesdato',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='firm',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='firm',
            name='municipality',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='firm',
            name='postal',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='firm',
            name='postalcode',
            field=models.CharField(default='', max_length=10),
        ),
    ]
