# Generated by Django 4.2.2 on 2023-09-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_firm_municipality_nr_firm_stiftelsesdato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firm',
            name='orgnr',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
