export const naceList = [
  "Administrasjon av finansmarkeder",
  "Agentur- og engroshandel med andre motorvogner, unntatt motorsykler",
  "Agentur- og engroshandel med biler og lette motorvogner, unntatt motorsykler",
  "Agentur- og engroshandel med deler og utstyr til motorvogner, unntatt motorsykler",
  "Agentur- og engroshandel med motorsykler, deler og utstyr",
  "Agenturhandel med bredt vareutvalg",
  "Agenturhandel med brensel, drivstoff, malm, metaller og industrikjemikalier",
  "Agenturhandel med maskiner, produksjonsutstyr, båter og luftfartøyer",
  "Agenturhandel med møbler, husholdningsvarer og jernvarer",
  "Agenturhandel med nærings- og nytelsesmidler",
  "Agenturhandel med spesialisert vareutvalg ellers",
  "Agenturhandel med tekstiler, klær, pelsskinn, skotøy og lærvarer",
  "Agenturhandel med tømmer, trelast og byggevarer",
  "Aktive eierfond",
  "Aktiviteter i andre interesseorganisasjoner ikke nevnt annet sted",
  "Allmenn legetjeneste",
  "Alminnelige somatiske sykehus",
  "Andre helsetjenester",
  "Andre informasjonstjenester ikke nevnt annet sted",
  "Andre kombinerte tjenester tilknyttet eiendomsdrift",
  "Andre post- og budtjenester",
  "Andre sosialtjenester uten botilbud",
  "Andre sportsaktiviteter",
  "Andre tjenester tilknyttet finansieringsvirksomhet",
  "Andre tjenester tilknyttet forsikringsvirksomhet og pensjonskasser",
  "Andre tjenester tilknyttet informasjonsteknologi",
  "Andre tjenester tilknyttet lufttransport",
  "Andre tjenester tilknyttet undervisning",
  "Andre tjenester tilknyttet utvinning av råolje og naturgass",
  "Annen bryting og utvinning ikke nevnt annet sted",
  "Annen faglig, vitenskapelig og teknisk virksomhet ikke nevnt annet sted",
  "Annen ferdiggjøring av bygninger",
  "Annen finansieringsvirksomhet ikke nevnt annet sted",
  "Annen forebyggende helsetjeneste",
  "Annen forretningsmessig tjenesteyting ikke nevnt annet sted",
  "Annen forskning og annet utviklingsarbeid innen naturvitenskap og teknikk",
  "Annen industriproduksjon ikke nevnt annet sted",
  "Annen kredittgivning",
  "Annen overnatting",
  "Annen rengjøringsvirksomhet ikke nevnt annet sted",
  "Annen spesialisert bygge- og anleggsvirksomhet",
  "Annen teknisk konsulentvirksomhet",
  "Annen undervisning ikke nevnt annet sted",
  "Annen undervisning innen kultur",
  "Annet fjørfehold",
  "Annet installasjonsarbeid",
  "Arbeidsmarkedskurs",
  "Arbeidstrening for ordinært arbeidsmarked",
  "Arkitekttjenester vedrørende byggverk",
  "Asylmottak",
  "Avlastningsboliger/-institusjoner",
  "Avvirkning",
  "Bankvirksomhet ellers",
  "Barnehager",
  "Barneverntjenester",
  "Bearbeiding av metaller",
  "Bearbeiding av planglass",
  "Bearbeiding av te og kaffe",
  "Bearbeiding og konservering av fjørfekjøtt",
  "Bearbeiding og konservering av frukt og grønnsaker ellers",
  "Bearbeiding og konservering av kjøtt",
  "Bearbeiding og konservering av poteter",
  "Bearbeiding og spinning av tekstilfibrer",
  "Bedriftsrådgivning og annen administrativ rådgivning",
  "Begravelsesbyråvirksomhet og drift av kirkegårder og krematorier",
  "Behandling og disponering av farlig avfall",
  "Behandling og disponering av ikke-farlig avfall",
  "Beplantning av hager og parkanlegg",
  "Blikkenslagerarbeid på tak",
  "Bofellesskap for eldre og funksjonshemmede med fast tilknyttet personell hele døgnet",
  "Bofellesskap for psykisk utviklingshemmede",
  "Bokbinding og tilknyttede tjenester",
  "Boretjenester tilknyttet utvinning av råolje og naturgass",
  "Borettslag",
  "Brannvern",
  "Bryting av ikke-jernholdig malm ellers",
  "Bryting av jernmalm",
  "Bryting av kalkstein, gips og kritt",
  "Bryting av skifer",
  "Bryting av stein til bygge- og anleggsvirksomhet",
  "Butikkhandel ikke nevnt annet sted",
  "Butikkhandel med antikviteter",
  "Butikkhandel med apotekvarer",
  "Butikkhandel med audio- og videoutstyr",
  "Butikkhandel med aviser og papirvarer",
  "Butikkhandel med bakervarer og konditorvarer",
  "Butikkhandel med belysningsutstyr",
  "Butikkhandel med blomster og planter",
  "Butikkhandel med bredt utvalg av jernvarer, fargevarer og andre byggevarer",
  "Butikkhandel med bredt vareutvalg ellers",
  "Butikkhandel med bredt vareutvalg med hovedvekt på nærings- og nytelsesmidler",
  "Butikkhandel med brukte klær",
  "Butikkhandel med brukte varer ellers",
  "Butikkhandel med byggevarer ikke nevnt annet sted",
  "Butikkhandel med bøker",
  "Butikkhandel med datamaskiner og utstyr til datamaskiner",
  "Butikkhandel med drikkevarer ellers",
  "Butikkhandel med elektriske husholdningsapparater",
  "Butikkhandel med fargevarer",
  "Butikkhandel med fisk, skalldyr og bløtdyr",
  "Butikkhandel med fotoutstyr",
  "Butikkhandel med fritidsbåter og -utstyr",
  "Butikkhandel med frukt og grønnsaker",
  "Butikkhandel med gardiner",
  "Butikkhandel med gull- og sølvvarer",
  "Butikkhandel med helsekost",
  "Butikkhandel med innredningsartikler ikke nevnt annet sted",
  "Butikkhandel med innspillinger av musikk og video",
  "Butikkhandel med jernvarer",
  "Butikkhandel med kaffe og te",
  "Butikkhandel med kjæledyr og fôr til kjæledyr",
  "Butikkhandel med kjøkkenutstyr, glass og steintøy",
  "Butikkhandel med kjøtt og kjøttvarer",
  "Butikkhandel med klær",
  "Butikkhandel med kosmetikk og toalettartikler",
  "Butikkhandel med medisinske og ortopediske artikler",
  "Butikkhandel med musikkinstrumenter og noter",
  "Butikkhandel med møbler",
  "Butikkhandel med nærings- og nytelsesmidler ikke nevnt annet sted",
  "Butikkhandel med optiske artikler",
  "Butikkhandel med reiseeffekter av lær og lærimitasjoner og varer av lær",
  "Butikkhandel med skotøy",
  "Butikkhandel med spill og leker",
  "Butikkhandel med sportsutstyr",
  "Butikkhandel med sukkervarer",
  "Butikkhandel med tapeter og gulvbelegg",
  "Butikkhandel med tekstiler og utstyrsvarer",
  "Butikkhandel med telekommunikasjonsutstyr",
  "Butikkhandel med tepper",
  "Butikkhandel med tobakksvarer",
  "Butikkhandel med trelast",
  "Butikkhandel med ur og klokker",
  "Butikkhandel med vin og brennevin",
  "Byggeteknisk konsulentvirksomhet",
  "Bygging av andre anlegg ikke nevnt annet sted",
  "Bygging av anlegg for elektrisitet og telekommunikasjon",
  "Bygging av bruer og tunneler",
  "Bygging av fritidsbåter",
  "Bygging av havne- og damanlegg",
  "Bygging av jernbaner og undergrunnsbaner",
  "Bygging av oljeplattformer og moduler",
  "Bygging av skip og skrog over 100 br.tonn",
  "Bygging av skip under 100 br.tonn",
  "Bygging av vann- og kloakkanlegg",
  "Bygging av veier og motorveier",
  "Cateringvirksomhet",
  "Dagsentra/aktivitetssentra for eldre og funksjonshemmede",
  "Damp- og varmtvannsforsyning",
  "Databehandling, datalagring og tilknyttede tjenester",
  "Destillering, rektifisering og blanding av sprit",
  "Detaljhandel med andre motorvogner, unntatt motorsykler",
  "Detaljhandel med biler og lette motorvogner, unntatt motorsykler",
  "Detaljhandel med deler og utstyr til motorvogner, unntatt motorsykler",
  "Detaljhandel med drivstoff til motorvogner",
  "Detaljhandel med motorsykler, deler og utstyr",
  "Detaljhandel utenom utsalgssted ellers",
  "Distribusjon av elektrisitet",
  "Distribusjon av film, video og fjernsynsprogrammer",
  "Distribusjon av gass gjennom ledningsnett",
  "Drift av barer ellers",
  "Drift av bomstasjoner",
  "Drift av botaniske og zoologiske hager og naturreservater",
  "Drift av campingplasser",
  "Drift av ferieleiligheter",
  "Drift av fornøyelses- og temaparker",
  "Drift av gatekjøkken",
  "Drift av gods- og transportsentraler",
  "Drift av havne- og kaianlegg",
  "Drift av historiske steder og bygninger og lignende severdigheter",
  "Drift av hoteller, pensjonater og moteller med restaurant",
  "Drift av hoteller, pensjonater og moteller uten restaurant",
  "Drift av idrettsanlegg",
  "Drift av kulturhistoriske museer",
  "Drift av kunst- og kunstindustrimuseer",
  "Drift av lokaler tilknyttet kunstnerisk virksomhet",
  "Drift av museer ikke nevnt annet sted",
  "Drift av parkeringsplasser og parkeringshus",
  "Drift av puber",
  "Drift av restauranter og kafeer",
  "Drift av taxisentraler og annen formidling av persontransport",
  "Drift av vandrerhjem",
  "Drift av web-portaler",
  "Drosjebiltransport",
  "Dyrking av annen frukt som vokser på trær eller busker samt nøtter",
  "Dyrking av druer",
  "Dyrking av ettårige vekster ellers",
  "Dyrking av flerårige vekster ellers",
  "Dyrking av grønnsaker, meloner, rot- og knollvekster",
  "Dyrking av kjernefrukter og steinfrukter",
  "Dyrking av korn (unntatt ris), belgvekster og oljeholdige vekster",
  "Dyrking av krydder og aromatiske, medisinske og farmasøytiske vekster",
  "Eiendomsforvaltning",
  "Eiendomsmegling",
  "Elektrisk installasjonsarbeid",
  "Engroshandel med avfall og skrap",
  "Engroshandel med belysningsutstyr",
  "Engroshandel med blomster og planter",
  "Engroshandel med bredt utvalg av nærings- og nytelsesmidler",
  "Engroshandel med byggevarer ikke nevnt annet sted",
  "Engroshandel med bøker, aviser og blader",
  "Engroshandel med datamaskiner, tilleggsutstyr til datamaskiner samt programvare",
  "Engroshandel med drikkevarer ellers",
  "Engroshandel med drivstoff og brensel",
  "Engroshandel med elektriske husholdningsapparater og -maskiner",
  "Engroshandel med elektronikkutstyr og telekommunikasjonsutstyr samt deler",
  "Engroshandel med fargevarer",
  "Engroshandel med fisk, skalldyr og bløtdyr",
  "Engroshandel med fotoutstyr",
  "Engroshandel med fritidsbåter og -utstyr",
  "Engroshandel med frukt og grønnsaker",
  "Engroshandel med gull- og sølvvarer",
  "Engroshandel med gulvtepper",
  "Engroshandel med huder, skinn og lær",
  "Engroshandel med husholdningsvarer og varer til personlig bruk ikke nevnt annet sted",
  "Engroshandel med innsatsvarer ikke nevnt annet sted",
  "Engroshandel med jernvarer, rørleggerartikler og oppvarmingsutstyr",
  "Engroshandel med kaffe, te, kakao og krydder",
  "Engroshandel med kjemiske produkter",
  "Engroshandel med kjøkkenutstyr, glass og steintøy",
  "Engroshandel med kjøtt og kjøttvarer",
  "Engroshandel med klokker og ur",
  "Engroshandel med klær",
  "Engroshandel med kontormøbler",
  "Engroshandel med korn, råtobakk, såvarer og fôrvarer",
  "Engroshandel med maskiner og utstyr til bergverksdrift, olje- og gassutvinning og bygge- og anleggsvirksomhet",
  "Engroshandel med maskiner og utstyr til handel, transport og tjenesteyting ellers",
  "Engroshandel med maskiner og utstyr til industri ellers",
  "Engroshandel med maskiner og utstyr til jordbruk og skogbruk",
  "Engroshandel med maskiner og utstyr til kontor ellers",
  "Engroshandel med maskiner og utstyr til kraftproduksjon og installasjon",
  "Engroshandel med maskinverktøy",
  "Engroshandel med meierivarer, egg, matolje og -fett",
  "Engroshandel med metaller og metallholdig malm",
  "Engroshandel med møbler",
  "Engroshandel med optiske artikler",
  "Engroshandel med papir og papp",
  "Engroshandel med parfyme og kosmetikk",
  "Engroshandel med plater, musikk- og videokassetter og CD- og DVD-plater",
  "Engroshandel med radio og fjernsyn",
  "Engroshandel med reiseeffekter og lærvarer",
  "Engroshandel med rengjøringsmidler",
  "Engroshandel med skipsutstyr og fiskeredskap",
  "Engroshandel med skotøy",
  "Engroshandel med spesialisert utvalg av nærings- og nytelsesmidler ikke nevnt annet sted",
  "Engroshandel med spill og leker",
  "Engroshandel med sportsutstyr",
  "Engroshandel med sukker, sjokolade og sukkervarer",
  "Engroshandel med sykepleie- og apotekvarer",
  "Engroshandel med tekstiler og utstyrsvarer",
  "Engroshandel med tobakksvarer",
  "Engroshandel med trelast",
  "Engroshandel med tømmer",
  "Engroshandel med vin og brennevin",
  "Etterarbeid knyttet til produksjon av film, video og fjernsynsprogramm er",
  "Etterbehandling av tekstiler",
  "Etterforskning",
  "Familieverntjenester",
  "Ferdiggjøring før trykking og publisering",
  "Ferskvannsfiske",
  "Filmframvisning",
  "Fjernsynskringkasting",
  "Flymegling",
  "Flyttetransport",
  "Fond/legater som støtter veldedige og allmennyttige formål",
  "Fondsforvaltningsvirksomhet",
  "Forlagsvirksomhet ellers",
  "Forsikringsformidling",
  "Forskning og utviklingsarbeid innen bioteknologi",
  "Forskning og utviklingsarbeid innen samfunnsvitenskap og humanistiske fag",
  "Forsyning og andre sjøtransporttjenester for offshore",
  "Forsyningsbaser",
  "Forvaltning og drift av IT-systemer",
  "Fotografvirksomhet",
  "Fotokopiering, forberedelse av dokumenter og andre spesialiserte kontortjenester",
  "Frisering og annen skjønnhetspleie",
  "Fritidsetablissement",
  "Fritidsklubber for barn og ungdom",
  "Fritidsvirksomhet ellers",
  "Frysing av fisk, fiskefileter, skalldyr og bløtdyr",
  "Fysioterapitjeneste",
  "Geitehold",
  "Generell offentlig administrasjon",
  "Geologiske undersøkelser",
  "Glassarbeid",
  "Godstransport med jernbane",
  "Godstransport på vei",
  "Grafisk og visuell kommunikasjonsdesign",
  "Grunnarbeid",
  "Guider og reiseledere",
  "Gulvlegging og tapetsering",
  "Handel med elektrisitet",
  "Hav- og kystfiske",
  "Hjemmehjelp",
  "Hjemmesykepleie",
  "Hogging og bearbeiding av monument- og bygningsstein",
  "Hold av verpehøner for konsumeggproduksjon",
  "Husdyrhold ellers",
  "Idrettslag og -klubber",
  "Impresariovirksomhet",
  "Industridesign, produktdesign og annen teknisk designvirksomhet",
  "Inkasso- og kredittopplysningsvirksomhet",
  "Innenlandske kystruter med passasjerer",
  "Innenriks sjøfart med gods",
  "Innrednings- og installasjonsarbeid utført på borerigger og moduler",
  "Innrednings- og installasjonsarbeid utført på skip over 100 br.tonn",
  "Innsamling av farlig avfall",
  "Innsamling av ikke-farlig avfall",
  "Innsamling av viltvoksende produkter av annet enn tre",
  "Installasjon av industrimaskiner og -utstyr",
  "Institusjoner i psykisk helsevern for barn og unge",
  "Institusjoner i psykisk helsevern for voksne",
  "Institusjoner innen barne- og ungdomsvern",
  "Interiørarkitekt, interiørdesign og interiørkonsulentvirksomhet",
  "Investeringsselskaper og lignende lukket for allmennheten",
  "Investeringsselskaper/-fond åpne for allmennheten",
  "Jakt, viltstell og tjenester tilknyttet jakt og viltstell",
  "Juridisk tjenesteyting",
  "Kabelbasert telekommunikasjon",
  "Kaldvalsing av bånd",
  "Kaldvalsing og pressing av profilerte plater og profiler",
  "Kantiner drevet som selvstendig virksomhet",
  "Kart og oppmåling",
  "Kioskhandel med bredt vareutvalg med hovedvekt på nærings- og nytelsesmidler",
  "Kjøp og salg av egen fast eiendom",
  "Klinisk psykologtjeneste",
  "Kombinert husdyrhold og planteproduksjon",
  "Kombinerte kontortjenester",
  "Kongress-, messe- og utstillingsvirksomhet",
  "Konsulentvirksomhet tilknyttet informasjonsteknologi",
  "Kuldeanlegg- og varmepumpearbeid",
  "Kysttrafikk ellers med passasjerer",
  "Lagring",
  "Landskapsarkitekttjenester",
  "Lasting og lossing",
  "Leasing av immateriell eiendom og lignende produkter, unntatt opphavsrettsbeskyttede verker",
  "Legetjenester innen psykisk helsevern",
  "Lotteri og totalisatorspill",
  "Lufttransport med gods",
  "Lufttransport med passasjerer",
  "Malerarbeid",
  "Markeds- og opinionsundersøkelser",
  "Medieformidlingstjenester",
  "Medisinske laboratorietjenester",
  "Melkeproduksjon på storfe",
  "Miljørydding, miljørensing og lignende virksomhet",
  "Modellbyråvirksomhet",
  "Nyhetsbyråer",
  "Næringslivs- og arbeidsgiverorganisasjoner",
  "Offentlig administrasjon tilknyttet næringsvirksomhet og arbeidsmarked",
  "Omsorgsinstitusjoner ellers",
  "Omsorgsinstitusjoner for rusmiddelmisbrukere",
  "Oppdrett av annet storfe",
  "Oppdrett av hester og andre dyr av hestefamilien",
  "Oppføring av bygninger",
  "Opplevelses-, arrangements- og aktivitetsarrangørvirksomhet",
  "Opplevelsesaktiviteter",
  "Oppsamling og behandling av avløpsvann",
  "Ordinær grunnskoleundervisning",
  "Overflatebehandling av metaller",
  "Overføring av elektrisitet",
  "Oversettelses- og tolkevirksomhet",
  "PR og kommunikasjonstjenester",
  "Pakkevirksomhet",
  "Passasjertransport med jernbane",
  "Passasjertransport på elver og innsjøer",
  "Pedagogisk-psykologisk rådgivningstjeneste",
  "Personlig tjenesteyting ikke nevnt annet sted",
  "Plan- og reguleringsarbeid",
  "Planteformering",
  "Postordre-/Internetthandel med IKT-utstyr",
  "Postordre-/Internetthandel med annet spesialisert vareutvalg",
  "Postordre-/Internetthandel med belysningsutstyr, kjøkkenutstyr, møbler og innredningsartikler",
  "Postordre-/Internetthandel med bredt vareutvalg",
  "Postordre-/Internetthandel med bøker, papir, aviser og blader",
  "Postordre-/Internetthandel med elektriske husholdningsapparater, radio, fjernsyn, plater, kassetter og musikkinstrumenter",
  "Postordre-/Internetthandel med helsekost",
  "Postordre-/Internetthandel med tekstiler, utstyrsvarer, klær, skotøy, reiseeffekter og lærvarer",
  "Preging av mynter og medaljer",
  "Private vakttjenester",
  "Produksjon av andre deler og annet utstyr til motorvogner",
  "Produksjon av andre elektroniske og elektriske ledninger og kabler",
  "Produksjon av andre ikke-destillerte gjærede drikkevarer",
  "Produksjon av andre klær av trikotasje",
  "Produksjon av andre organiske kjemiske råvarer",
  "Produksjon av andre rør og rørdeler av stål",
  "Produksjon av andre tanker, cisterner og beholdere av metall",
  "Produksjon av andre tekstilvarer, unntatt klær",
  "Produksjon av andre trevarer og varer av kork, strå og flettematerialer",
  "Produksjon av andre uorganiske kjemikalier",
  "Produksjon av annet elektrisk utstyr",
  "Produksjon av annet flytende materiell",
  "Produksjon av annet yttertøy",
  "Produksjon av basisplast",
  "Produksjon av batterier og akkumulatorer",
  "Produksjon av belysningsutstyr",
  "Produksjon av betong-, sement- og gipsprodukter ellers",
  "Produksjon av betongprodukter for bygge- og anleggsvirksomhet",
  "Produksjon av bijouteri og lignende artikler",
  "Produksjon av bly, sink og tinn",
  "Produksjon av bolter og skruer",
  "Produksjon av brød og ferske konditorvarer",
  "Produksjon av byggevarer av plast",
  "Produksjon av bygningsartikler",
  "Produksjon av bølgepapp og emballasje av papir og papp",
  "Produksjon av dampkjeler, unntatt kjeler til sentralvarmeanlegg",
  "Produksjon av datamaskiner og tilleggsutstyr",
  "Produksjon av dører og vinduer av metall",
  "Produksjon av eksplosiver",
  "Produksjon av elektrisitet ellers",
  "Produksjon av elektrisitet fra biobrensel, avfallsforbrenning og deponigass",
  "Produksjon av elektrisitet fra vannkraft",
  "Produksjon av elektrisitet fra vindkraft",
  "Produksjon av elektrisk og elektronisk utstyr til motorvogner",
  "Produksjon av elektriske fordelings- og kontrolltavler og paneler",
  "Produksjon av elektriske husholdningsmaskiner og -apparater",
  "Produksjon av elektromotorer, generatorer og transformatorer",
  "Produksjon av elektronikk til husholdningsbruk",
  "Produksjon av elektroniske komponenter",
  "Produksjon av emballasje og husholdningsartikler av glass og krystall",
  "Produksjon av eteriske oljer",
  "Produksjon av farmasøytiske preparater",
  "Produksjon av farmasøytiske råvarer",
  "Produksjon av ferdigblandet betong",
  "Produksjon av ferdigmat",
  "Produksjon av ferrolegeringer",
  "Produksjon av film, video og fjernsynsprogrammer",
  "Produksjon av finerplater og andre bygnings- og møbelplater av tre",
  "Produksjon av fiskehermetikk",
  "Produksjon av fôrvarer til husdyrhold",
  "Produksjon av gass",
  "Produksjon av gjødsel, nitrogenforbindelser og vekstjord",
  "Produksjon av glassfibrer",
  "Produksjon av gull- og sølvvarer og lignende artikler",
  "Produksjon av gummidekk og slanger til gummidekk, og regummiering og vulkanisering av gummidekk",
  "Produksjon av gummiprodukter ellers",
  "Produksjon av halvfabrikater av aluminium",
  "Produksjon av halvfabrikater av plast",
  "Produksjon av homogeniserte matprodukter og diettmat",
  "Produksjon av håndverktøy",
  "Produksjon av ikke-jernholdige metaller ellers",
  "Produksjon av ikke-metallholdige mineralprodukter ikke nevnt annet sted",
  "Produksjon av ildfaste produkter",
  "Produksjon av industri- og laboratorieovner samt brennere",
  "Produksjon av industrigasser",
  "Produksjon av iskrem",
  "Produksjon av isolatorer og isoleringsdeler av keramisk materiale",
  "Produksjon av jern og stål",
  "Produksjon av jordbruks- og skogbruksmaskiner",
  "Produksjon av juice av frukt og grønnsaker",
  "Produksjon av kakao, sjokolade og sukkervarer",
  "Produksjon av kalk og gips",
  "Produksjon av karosserier og tilhengere",
  "Produksjon av keramiske husholdningsartikler og dekorasjonsgjenstander",
  "Produksjon av kjemiske produkter ikke nevnt annet sted",
  "Produksjon av kjøkkenmøbler",
  "Produksjon av kjøkkenredskaper og skjære- og klipperedskaper",
  "Produksjon av kjøle- og ventilasjonsanlegg, unntatt til husholdningsbruk",
  "Produksjon av kjøtt- og fjørfevarer",
  "Produksjon av klokker og ur",
  "Produksjon av klær av lær",
  "Produksjon av klær og tilbehør ellers",
  "Produksjon av kommunikasjonsutstyr",
  "Produksjon av komponenter til hydraulisk og pneumatisk utstyr",
  "Produksjon av kontor- og butikkmøbler",
  "Produksjon av kornvarer",
  "Produksjon av koster og børster",
  "Produksjon av kraner og ventiler ellers",
  "Produksjon av kretskort",
  "Produksjon av lagre, gir, tannhjulsutvekslinger og andre innretninger for kraftoverføring",
  "Produksjon av ledningsmateriell",
  "Produksjon av låser og beslag",
  "Produksjon av løfte- og håndteringsutstyr ellers",
  "Produksjon av løfte- og håndteringsutstyr til skip og båter",
  "Produksjon av madrasser",
  "Produksjon av magnetiske og optiske media",
  "Produksjon av maling og lakk, trykkfarger og tetningsmidler",
  "Produksjon av maskiner og utstyr til bergverksdrift og bygge- og anleggsvirksomhet",
  "Produksjon av maskiner og utstyr til generell bruk, ikke nevnt annet sted",
  "Produksjon av maskiner og utstyr til metallurgisk industri",
  "Produksjon av maskiner og utstyr til nærings- og nytelsesmiddelindustri",
  "Produksjon av maskinverktøy ikke nevnt annet sted",
  "Produksjon av matfisk og skalldyr i ferskvannsbasert fiskeoppdrett",
  "Produksjon av matfisk og skalldyr i hav- og kystbasert fiskeoppdrett",
  "Produksjon av medisinske og tanntekniske instrumenter og utstyr",
  "Produksjon av meierivarer",
  "Produksjon av metallkonstruksjoner og deler",
  "Produksjon av metallvarer ikke nevnt annet sted",
  "Produksjon av mineralvann, leskedrikker og annet vann på flaske",
  "Produksjon av monteringsferdige hus",
  "Produksjon av motorer og turbiner, unntatt motorer til luftfartøyer og motorvogner",
  "Produksjon av motorsykler",
  "Produksjon av motorvogner",
  "Produksjon av musikkinstrumenter",
  "Produksjon av måle-, kontroll- og navigasjonsinstrumenter",
  "Produksjon av møbler ellers",
  "Produksjon av mørtel",
  "Produksjon av næringsmidler ikke nevnt annet sted",
  "Produksjon av optiske instrumenter og fotografisk utstyr",
  "Produksjon av papir og papp",
  "Produksjon av parfyme og toalettartikler",
  "Produksjon av pelsvarer",
  "Produksjon av planglass",
  "Produksjon av plastemballasje",
  "Produksjon av plastprodukter ellers",
  "Produksjon av primæraluminium",
  "Produksjon av pumper og kompressorer ellers",
  "Produksjon av raffinerte petroleumsprodukter",
  "Produksjon av reiseeffekter og salmakerartikler",
  "Produksjon av rå fiskeoljer og fett",
  "Produksjon av saltfisk, tørrfisk og klippfisk",
  "Produksjon av sanitærutstyr av keramisk materiale",
  "Produksjon av sement",
  "Produksjon av skotøy",
  "Produksjon av smakstilsettingsstoffer og krydderier",
  "Produksjon av spesialmaskiner ikke nevnt annet sted",
  "Produksjon av spill og leker",
  "Produksjon av sportsartikler",
  "Produksjon av stoffer av trikotasje",
  "Produksjon av strømpevarer",
  "Produksjon av sykler og invalidevogner",
  "Produksjon av såpe og vaskemidler, rense- og polermidler",
  "Produksjon av tapeter",
  "Produksjon av tauverk og nett",
  "Produksjon av teknisk glass og andre glassvarer",
  "Produksjon av tekstiler ikke nevnt annet sted",
  "Produksjon av tekstiler til teknisk og industriell bruk",
  "Produksjon av treemballasje",
  "Produksjon av undertøy og innertøy",
  "Produksjon av utstyrsvarer",
  "Produksjon av varer av metalltråd, kjetting og fjærer",
  "Produksjon av varer av papir og papp ellers",
  "Produksjon av vin",
  "Produksjon av våpen og ammunisjon",
  "Produksjon av yngel og settefisk i ferskvannsbasert fiskeoppdrett",
  "Produksjon av yngel og settefisk i hav- og kystbasert fiskeoppdrett",
  "Produksjon av øl",
  "Produksjon og utgivelse av musikk- og lydopptak",
  "Programmeringstjenester",
  "Prøveboring",
  "Radiokringkasting",
  "Redningstjeneste",
  "Regnskap og bokføring",
  "Rehabilitering- og opptreningsinstitusjoner",
  "Reisearrangørvirksomhet",
  "Reisebyråvirksomhet",
  "Reklamebyråer",
  "Rekruttering og formidling av arbeidskraft",
  "Religiøse organisasjoner",
  "Rengjøring av bygninger",
  "Reparasjon av andre husholdningsvarer og varer til personlig bruk",
  "Reparasjon av annet utstyr",
  "Reparasjon av bearbeidede metallprodukter",
  "Reparasjon av datamaskiner og tilleggsutstyr",
  "Reparasjon av elektrisk utstyr",
  "Reparasjon av elektronikk til husholdningsbruk",
  "Reparasjon av elektronisk og optisk utstyr",
  "Reparasjon av husholdningsvarer og hageredskaper",
  "Reparasjon av kommunikasjonsutstyr",
  "Reparasjon av maskiner",
  "Reparasjon av møbler og boliginnredning",
  "Reparasjon av skotøy og lærvarer",
  "Reparasjon av ur, gull- og sølvvarer",
  "Reparasjon og vedlikehold av andre transportmidler",
  "Reparasjon og vedlikehold av luftfartøyer og romfartøyer",
  "Reparasjon og vedlikehold av skip og båter",
  "Reproduksjon av innspilte opptak",
  "Revisjon",
  "Risiko- og skadevurdering",
  "Riving av bygninger og andre konstruksjoner",
  "Rutebiltransport i by- og forstadsområde",
  "Rutebiltransport utenfor by- og forstadsområde",
  "Rørleggerarbeid",
  "Rørtransport",
  "Saging, høvling og impregnering av tre",
  "Satellittbasert telekommunikasjon",
  "Sauehold",
  "Selvstendig kunstnerisk virksomhet ikke nevnt annet sted",
  "Selvstendig kunstnerisk virksomhet innen blogging",
  "Selvstendig kunstnerisk virksomhet innen litteratur",
  "Selvstendig kunstnerisk virksomhet innen musikk",
  "Selvstendig kunstnerisk virksomhet innen scenekunst",
  "Selvstendig kunstnerisk virksomhet innen visuell kunst",
  "Skadedyrkontroll",
  "Skadeforsikring",
  "Skatterådgivning",
  "Skipsmegling",
  "Skogskjøtsel og andre skogbruksaktiviteter",
  "Slakting, bearbeiding og konservering av fisk og fiskevarer ellers",
  "Slepebåter",
  "Smiing, stansing og valsing av metall, og pulvermetallurgi",
  "Snekkerarbeid",
  "Somatiske poliklinikker",
  "Somatiske spesialsykehus",
  "Somatiske sykehjem",
  "Sortering og bearbeiding av avfall for materialgjenvinning",
  "Sosialtjenester for rusmiddelmisbrukere uten botilbud",
  "Spedisjon",
  "Spesialisert legetjeneste, unntatt psykiatrisk legetjeneste",
  "Spesielle holdingselskaper",
  "Stikking av torv",
  "Studieforbunds- og frivillige organisasjoners kurs",
  "Støping av andre ikke-jernholdige metaller",
  "Støping av jern",
  "Støping av lettmetaller",
  "Støping av stål",
  "Svinehold",
  "Takarbeid ellers",
  "Takseringsvirksomhet",
  "Tannhelsetjenester",
  "Teknisk prøving og analyse",
  "Telefonsalg",
  "Telefonvakttjenester",
  "Telekommunikasjon ellers",
  "Timelærervirksomhet",
  "Tjenester tilknyttet annen bergverksdrift",
  "Tjenester tilknyttet ferskvannsbasert fiskeoppdrett",
  "Tjenester tilknyttet hav- og kystbasert fiskeoppdrett",
  "Tjenester tilknyttet husdyrhold",
  "Tjenester tilknyttet landtransport ellers",
  "Tjenester tilknyttet planteproduksjon",
  "Tjenester tilknyttet sjøtransport ellers",
  "Tjenester tilknyttet skogbruk",
  "Tjenester tilknyttet underholdningsvirksomhet",
  "Tjenester tilknyttet vakttjenester",
  "Torghandel med andre varer",
  "Torghandel med næringsmidler, drikkevarer og tobakksvarer",
  "Trafikkskoleundervisning",
  "Transport med taubaner, kabelbaner og skiheiser",
  "Transportformidling ellers",
  "Treningssentre",
  "Trykking av aviser",
  "Trykking ellers",
  "Trådløs telekommunikasjon",
  "Turbiltransport",
  "Turistkontorvirksomhet og destinasjonsselskaper",
  "Turistrelaterte tjenester ikke nevnt annet sted",
  "Undervisning i kunstfag",
  "Undervisning innen idrett og rekreasjon",
  "Undervisning ved andre høgskoler",
  "Undervisning ved fagskoler",
  "Uoppgitt",
  "Uspesifisert engroshandel",
  "Utenriks sjøfart med gods",
  "Utenriks sjøfart med passasjerer",
  "Utgivelse av annen programvare",
  "Utgivelse av aviser",
  "Utgivelse av blader og tidsskrifter",
  "Utgivelse av bøker",
  "Utgivelse av programvare for dataspill",
  "Utleie av arbeidskraft",
  "Utleie av egen eller leid fast eiendom ellers",
  "Utleie og leasing av andre husholdningsvarer og varer til personlig bruk",
  "Utleie og leasing av andre maskiner og annet utstyr og materiell ikke nevnt annet sted",
  "Utleie og leasing av biler og andre lette motorvogner",
  "Utleie og leasing av bygge- og anleggsmaskiner og -utstyr",
  "Utleie og leasing av kontor- og datamaskiner",
  "Utleie og leasing av landbruksmaskiner og -utstyr",
  "Utleie og leasing av lastebiler",
  "Utleie og leasing av lufttransportmateriell",
  "Utleie og leasing av sjøtransportmateriell",
  "Utleie og leasing av sports- og fritidsutstyr",
  "Uttak fra kilde, rensing og distribusjon av vann",
  "Utvendig rengjøring av bygninger og industriell rengjøring",
  "Utvikling og salg av egen fast eiendom ellers",
  "Utvinning av råolje",
  "Utvinning av salt",
  "Utvinning fra grus- og sandtak, og utvinning av leire og kaolin",
  "Utøvende kunstnere og underholdningsvirksomhet ikke nevnt annet sted",
  "Utøvende kunstnere og underholdningsvirksomhet innen musikk",
  "Utøvende kunstnere og underholdningsvirksomhet innen scenekunst",
  "Vaktmestertjenester",
  "Varig tilrettelagt arbeid",
  "Vaskeri- og renserivirksomhet",
  "Vedlikehold og reparasjon av motorsykler",
  "Vedlikehold og reparasjon av motorvogner, unntatt motorsykler",
  "Ventilasjonsarbeid",
  "Verdipapirmegling",
  "Veterinærtjenester",
  "Veving av tekstiler",
  "Videregående opplæring innen allmennfaglige studieretninger",
  "Videregående opplæring innen tekniske og andre yrkesfaglige studieretninger",
  "Virksomhet knyttet til kroppspleie og fysisk velvære",
  "Voksenopplæringssentre",
];
